"""empty message

Revision ID: 3a5639b428a3
Revises: 53bc7c98bf1
Create Date: 2014-08-20 19:43:58.064434

"""

# revision identifiers, used by Alembic.
revision = '3a5639b428a3'
down_revision = '53bc7c98bf1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
